### ISSUE TITLE
Packages in fresh OpenWRT compile for AR150

### ISSUE THREAD

**Issue by OpenFerret** [domino-team/openwrt-cc#12]
Hi there,

I'm going to compile OpenWRT 15.05 from source using the build system and your patch.

Can you add to the wiki any information on what default packages are required for a clean install with working interfaces (wifi, ethernet and USB), or does the default make config once you've selected the correct target work straight away?

I don't require GUI access, but need to be able to connect to the router and configure various aspects of the router (wifi, VPN, TOR, etc).

If GUI access needs to be afforded as CLI access requires config first then I would prefer LuCI over the GLI interface.

Many thanks!

**Comment by alzhao** [comment]
sorry for replying late. Just missed this in github. We can write some docs about how to config. But you never can have the same firmware as the stock firmware. There is too many details to take care.

**Comment by sholwe** [comment]
Is there any hope to get LEDE for the MT-300x (not NAND based) series?  How about some newer hardware?  I missed out on the short sale of the GL-AR300MD- but it sounds like the 5Ghz support is pretty close to bit-banged for now?

**Comment by alzhao** [comment]
Now we have more 5G modules and later we will migrate all firmware to LEDE 17.01

**Comment by sholwe** [comment]
Awesome! Thanks for the update.
