### ISSUE TITLE
Supporting LEDE

### ISSUE THREAD

**Issue by milani** [domino-team/openwrt-cc#14]
As you know, openwrt does not get more updates after main contributors migrated to LEDE project. I wish you could add patches to LEDE to have new updates there too.

**Comment by tedaz** [comment]
Great suggestion, looking forward the author could submit the patches to LEDE team.

**Comment by milani** [comment]
Also new improvements made on this repo, the targets are mostly available in LEDE. But I couldn't find NAND flash target for AR300M among them.

**Comment by alzhao** [comment]
https://github.com/domino-team/lede-ar300m

I made a fork and added AR300M nand flash support. Still need sometime to clean the driver and get it accepted.
