### ISSUE TITLE
Apply patches to CC failed

### ISSUE THREAD

**Issue by tedaz** [domino-team/openwrt-cc#15]
I tried to apply the patches to the official CC code (rather than git clone this project), during the building process, I got below error message:

Applying /chaos_calmer/target/linux/generic/patches-3.18/030-backport_bcm47xx_nvram.patch using plaintext: 
The next patch would create the file include/linux/bcm47xx_nvram.h,
which already exists!  Applying it anyway.
patching file include/linux/bcm47xx_nvram.h
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- saving rejects to file include/linux/bcm47xx_nvram.h.rej
Patch failed!  Please fix /chaos_calmer/target/linux/generic/patches-3.18/030-backport_bcm47xx_nvram.patch!
Makefile:100: recipe for target '/chaos_calmer/build_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/linux-3.18.27/.prepared' failed
make[3]: *** [/chaos_calmer/build_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/linux-3.18.27/.prepared] Error 1
make[3]: Leaving directory '/chaos_calmer/toolchain/kernel-headers'
toolchain/Makefile:81: recipe for target 'toolchain/kernel-headers/prepare' failed
make[2]: *** [toolchain/kernel-headers/prepare] Error 2
make[2]: Leaving directory '/chaos_calmer'
toolchain/Makefile:80: recipe for target '/chaos_calmer/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/stamp/.toolchain_install' failed
make[1]: *** [/chaos_calmer/staging_dir/toolchain-mipsel_24kec+dsp_gcc-4.8-linaro_uClibc-0.9.33.2/stamp/.toolchain_install] Error 2
make[1]: Leaving directory '/chaos_calmer'
/chaos_calmer/include/toplevel.mk:181: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by alzhao** [comment]
Hi, openwrt cc1505.1 keep adding more target which cause the patches failed to apply. Need to revert back to some commit before so that the patches can apply. But I didn't keep a record which commit it is.

**Comment by tedaz** [comment]
Is it possible to submit the GL.iNet target patches to the LEDE project? As the LEDE is actively developing now, and it is using the OpenWRT repo.
Alternatively, it is possible to release patches for CC 15.05.1?

**Comment by alzhao** [comment]
Actually we have already submitted all the patches to LEDE. Now only ar300m nand flash patch is not accepted.

**Comment by milani** [comment]
@alzhao Is there a reason it is not accepted? Would you please contact them to resolve the possible issues? AR300M is a capable board and I think it is losing attention because people can not run the latest LEDE on it.

**Comment by blogic** [comment]
@alzhao did you ever try to test the staging driver or help clean up the driver you submitted as per our feedback ?

**Comment by alzhao** [comment]
Thanks John. I didn't get a time to try but I will try asap.

@Morteza, in LEDE trunk seems there is a nand driver already and I need to
use that in order to get it accepted.

**Comment by alzhao** [comment]
@john,

Now I spent 2 days to understand and compare driver for ath79_spinand with
mt29f_spinand. Yes the code of ath79_spinand comes from mt29f_spinand. I
tried to clean up the code and patch mt29f instead. But seems this is too
difficult. New structs are defined and most of the functions are rewritten.
Only 5 functions can be reused and all the others will need to be patched
heavily. For me it is like a rewritten of the old driver and test it.
Furthermore, I am not sure after patch if the old driver still works with
mt29f spinand devices.

So, I decide just leave the code as is. Is it possible that the code can be
accepted if I resubmit it again to LEDE? Otherwise I will fork LEDE and
host it in my github for now.

Best,
Alfie

**Comment by alzhao** [comment]
https://github.com/domino-team/lede-ar300m

I made a fork and added AR300M nand flash support. Still need sometime to clean the driver and get it accepted.
