### ISSUE TITLE
mt300a target

### ISSUE THREAD

**Issue by bobdenardd** [domino-team/openwrt-cc#21]
Hi  there

When applying make menuconfig I cannot find any suitable target (well at least it seems to me). I don't see anything related to the Mediatek cpu built in mt300a router. Could you please help me out on this one?

Many thanks!

**Comment by alzhao** [comment]
Pls choose ramips first. 
Default is ar71xx, which is a different platform.

**Comment by bobdenardd** [comment]
Thanks a lot for your very quick answer :)

**Comment by luangong** [comment]
Select the following:

- Target System: **Ralink RT288x/RT3xxx**
- Subtarget: **MT7620 based boards**
- Target Profile: **GL-MT300A**

Ralink was aquired by MediaTek, so MT67620A/N is an `ramips` SoC.

See https://wiki.openwrt.org/doc/hardware/soc/soc.mediatek for more info.

**Comment by bobdenardd** [comment]
Yep, that's what I ended up doing, works like a charm, thanks a bunch! (what got me in trouble is that I didn't know that Ralink was bought by Mediatek)

**Comment by luangong** [comment]
@bobdenardd The target name “Ralink RT288x/RT3xxx” is a bit confusing. In LEDE, it is renamed as “MediaTek Ralink MIPS”, which is more meaningful.
